<a href="https://colab.research.google.com/github/mikashaw/ML-Projects/blob/main/C-CNN-EEGNET/CompactCNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import tensorflow as tf
import numpy as np
import scipy.io

In [2]:
# build tensorflow model from scratch
# use tensorflow  

In [3]:
!git clone https://github.com/aliasvishnu/EEGNet.git

Cloning into 'EEGNet'...
remote: Enumerating objects: 33, done.
remote: Total 33 (delta 0), reused 0 (delta 0), pack-reused 33
Unpacking objects: 100% (33/33), done.


In [4]:
!git clone https://github.com/mnakanishi/12JFPM_SSVEP.git

Cloning into '12JFPM_SSVEP'...
remote: Enumerating objects: 43, done.
remote: Total 43 (delta 0), reused 0 (delta 0), pack-reused 43
Unpacking objects: 100% (43/43), done.
Checking out files: 100% (13/13), done.


In [5]:
# load in data for one user

data = scipy.io.loadmat("/content/12JFPM_SSVEP/data/s1.mat")

In [43]:

# preprocess and reshaoe the data

#make a different class if want to split into train and test


class Preprocess:

  """preprocesses data with shape [Number of targets, Number of channels, Number of sampling points, Number of trials] 
  returning x_train and y_train dataset"""

  def __init__(self, data):

    self.data = data

    self._num_targets = None
    self._num_channels = None
    self._num_sampling_points = None
    self._num_trials = None 

  def process(self):
    """
    main public function: 
    Returns: reshaped data to shape [trials, samples, channels] in the form of a numpy array
    """

    # get data in the form of an numpy array
    np_data = self._to_numpy_array(self.data)
    #reshape the array to the desired format
    reshaped_arr = self._reshape_data(np_data)
    # get the training labels from the dataset and strip off labels from the data
    np_data, labels = self._get_labels(reshaped_arr)

    return np_data, labels

  def _to_numpy_array(self, data):

    data= np.array(data['eeg'], dtype='float32')

    #set properties
    self._num_targets = data.shape[0]
    self._num_channels = data.shape[1]
    self._num_sampling_points = data.shape[2]
    self._num_trials = data.shape[3]

    return data

  def _reshape_data(self, data):

    reshaped_data = data.reshape(self._num_targets, self._num_trials,1, self._num_sampling_points, self._num_channels)
    return reshaped_data
    

  def _get_labels(self, data):

    #get a labels for every sample in a trial there are 8 chennels 

    labels = []
    
    for class_num in range(0, self._num_targets):
      labels.append(([class_num]*self._num_trials*self._num_sampling_points))

    data= data[0,:,:,:]
    
    labels = np.array(np.squeeze(labels))

    return data, labels 





In [44]:
preprocessor = Preprocess(data)

In [45]:
x_train, y_train = preprocessor.process()

In [46]:
x_train.shape

(15, 1, 1114, 8)

In [1]:
d = [4,5,6,6]

In [14]:
l = []
l.append(([9]*4*5))
l.append([8]*4*5)

In [15]:
l

[[9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
 [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8]]

In [11]:
l = np.array()

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [ ]:
d = np.array(d)

In [ ]:
fat_array = np.array([[[[1]]]])

In [ ]:
fat_array.shape

(1, 1, 1, 1)

In [ ]:
fat_array = fat_array[:,:,:]

In [ ]:
fat_array

array([], shape=(0, 1, 1, 1), dtype=int64)

In [ ]:
arr = np.array([[[4,6,7], [4,5,6]]])
arr

array([[[4, 6, 7],
        [4, 5, 6]]])

In [ ]:
arr = np.squeeze(arr)
arr

array([[4, 6, 7],
       [4, 5, 6]])

array([[4, 6, 7],
       [4, 5, 6]])